# Generated by Django 6.1 on 2026-09-17 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor', models.CharField(db_index=True, help_text='Hash de la IP', max_length=64, verbose_name='visitante')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='titulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'conversacion',
                'verbose_name_plural': 'conversaciones',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['visitor', '-updated_at'], name='chat_conver_visitor_5726f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=16, verbose_name='rol')),
                ('content', models.TextField(verbose_name='contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='conversacion')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx')],
            },
        ),
    ]
