# Generated by Django 6.1 on 2026-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='scope',
            field=models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida')], default='general', max_length=16, verbose_name='alcance'),
        ),
    ]
