# Generated by Django 6.1 on 2026-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(help_text='Hash de la IP', max_length=64, verbose_name='visitante')),
                ('scope', models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida')], max_length=16, verbose_name='alcance')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='mensajes gastados')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultimo mensaje')),
            ],
            options={
                'verbose_name': 'cupo del chat',
                'verbose_name_plural': 'cupos del chat',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('visitor', 'scope'), name='cupo_unico_por_visitante_y_alcance')],
            },
        ),
    ]
