# Generated by Django 6.1 on 2026-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquota',
            name='scope',
            field=models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida'), ('finanzas', 'Finanzas personales')], max_length=16, verbose_name='alcance'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='scope',
            field=models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida'), ('finanzas', 'Finanzas personales')], default='general', max_length=16, verbose_name='alcance'),
        ),
    ]
