# Generated by Django 6.1 on 2026-09-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatquota_scope_alter_conversation_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquota',
            name='scope',
            field=models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida'), ('finanzas', 'Finanzas personales'), ('consejos', 'Consejos sobre un chat de WhatsApp')], max_length=16, verbose_name='alcance'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='scope',
            field=models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida'), ('finanzas', 'Finanzas personales'), ('consejos', 'Consejos sobre un chat de WhatsApp')], default='general', max_length=16, verbose_name='alcance'),
        ),
        migrations.CreateModel(
            name='AnalisisConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(db_index=True, help_text='Hash de la IP', max_length=64, verbose_name='visitante')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del archivo')),
                ('participantes', models.JSONField(default=list, verbose_name='participantes')),
                ('total_mensajes', models.PositiveIntegerField(default=0, verbose_name='mensajes')),
                ('desde', models.CharField(blank=True, max_length=40, verbose_name='primer mensaje')),
                ('hasta', models.CharField(blank=True, max_length=40, verbose_name='ultimo mensaje')),
                ('contenido', models.TextField(verbose_name='conversacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='subido')),
            ],
            options={
                'verbose_name': 'análisis de conversación',
                'verbose_name_plural': 'análisis de conversaciones',
                'db_table': 'analisis_conversaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visitor', '-created_at'], name='analisis_co_visitor_ab265a_idx')],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='chat.analisisconversacion', verbose_name='chat de contexto'),
        ),
    ]
