# Generated by Django 6.1 on 2026-09-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_analisis_conversaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisconversacion',
            name='borrado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='oculto por el visitante'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='borrada_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='oculta por el visitante'),
        ),
    ]
