# Generated by Django 6.1 on 2026-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_ocultar_en_vez_de_borrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisconversacion',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminado definitivamente'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='eliminada_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminada definitivamente'),
        ),
    ]
