# Generated by Django 6.1 on 2026-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_eliminar_definitivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesConsejero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_caracteres', models.PositiveIntegerField(default=500, verbose_name='largo máximo de las respuestas (caracteres)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'ajustes del consejero',
                'verbose_name_plural': 'ajustes del consejero',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(help_text='Hash de la IP', max_length=64, unique=True, verbose_name='visitante')),
                ('groseria', models.CharField(choices=[('suave', 'Suave'), ('normal', 'Normal'), ('sin_filtro', 'Sin filtro')], default='normal', max_length=16, verbose_name='nivel de grosería')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'preferencia del visitante',
                'verbose_name_plural': 'preferencias de los visitantes',
            },
        ),
        migrations.AddField(
            model_name='analisisconversacion',
            name='interes',
            field=models.JSONField(blank=True, null=True, verbose_name='nivel de interés'),
        ),
    ]
