# Generated by Django 6.1 on 2026-09-25 17:54

from django.db import migrations, models


def largo_corto(apps, schema_editor):
    """Quien seguia con el default viejo (500) pasa al nuevo (200)."""
    apps.get_model("chat", "AjustesConsejero").objects.filter(
        max_caracteres=500
    ).update(max_caracteres=200)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_estadisticas_interes_ajustes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustesconsejero',
            name='max_caracteres',
            field=models.PositiveIntegerField(default=200, verbose_name='largo máximo de las respuestas (caracteres)'),
        ),
        migrations.AlterField(
            model_name='preferenciavisitante',
            name='groseria',
            field=models.CharField(choices=[('suave', 'Suave'), ('normal', 'Normal'), ('sin_filtro', 'Sin filtro')], default='sin_filtro', max_length=16, verbose_name='nivel de grosería'),
        ),
        migrations.RunPython(largo_corto, migrations.RunPython.noop),
    ]
