# Generated by Django 6.1 on 2026-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_defaults_200_sin_filtro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisisconversacion',
            name='interes',
        ),
        migrations.AddField(
            model_name='analisisconversacion',
            name='relacion',
            field=models.CharField(blank=True, choices=[('amistad', 'Amigo o amiga'), ('pareja', 'Pareja'), ('me_gusta', 'Me gusta'), ('amante', 'Amante'), ('ex', 'Ex'), ('familia', 'Familiar'), ('trabajo', 'Trabajo o estudio'), ('otra', 'Otra')], max_length=16, verbose_name='relación'),
        ),
        migrations.AddField(
            model_name='analisisconversacion',
            name='yo',
            field=models.CharField(default='Tú', max_length=120, verbose_name='quien lo subió'),
        ),
    ]
