# Generated by Django 6.1 on 2026-09-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_relacion_y_yo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisconversacion',
            name='perfil',
            field=models.JSONField(blank=True, default=dict, verbose_name='contexto que dio'),
        ),
    ]
