# Generated by Django 6.1 on 2026-09-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_perfil_del_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciavisitante',
            name='personalidad',
            field=models.CharField(choices=[('consejero', 'Consejero'), ('amigo', 'Amigo sincero'), ('psicologo', 'Psicólogo'), ('abuela', 'Tu abuela'), ('coach', 'Coach de conquista'), ('chismosa', 'Mejor amiga chismosa')], default='consejero', max_length=16, verbose_name='personalidad'),
        ),
    ]
