# Generated by Django 6.1 on 2026-09-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_personalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciavisitante',
            name='sin_limite',
            field=models.BooleanField(default=False, verbose_name='mensajes ilimitados'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(help_text='Hash de la IP', max_length=64, verbose_name='visitante')),
                ('util', models.BooleanField(verbose_name='le sirvió')),
                ('personalidad', models.CharField(blank=True, max_length=16, verbose_name='personalidad')),
                ('groseria', models.CharField(blank=True, max_length=16, verbose_name='nivel de grosería')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('mensaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to='chat.message', verbose_name='respuesta')),
            ],
            options={
                'verbose_name': 'valoración',
                'verbose_name_plural': 'valoraciones',
                'ordering': ['-updated_at'],
            },
        ),
    ]
