# Generated by Django 6.1 on 2026-09-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_valoraciones_y_sin_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquota',
            name='extra',
            field=models.PositiveIntegerField(default=0, verbose_name='mensajes desbloqueados'),
        ),
    ]
