# Generated by Django 6.1 on 2026-10-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_cupo_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquota',
            name='scope',
            field=models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida'), ('finanzas', 'Finanzas personales'), ('consejos', 'Consejos sobre un chat de WhatsApp'), ('creditos', 'Asesor de créditos y deudas')], max_length=16, verbose_name='alcance'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='scope',
            field=models.CharField(choices=[('general', 'Asistente general'), ('resume', 'Solo la hoja de vida'), ('finanzas', 'Finanzas personales'), ('consejos', 'Consejos sobre un chat de WhatsApp'), ('creditos', 'Asesor de créditos y deudas')], default='general', max_length=16, verbose_name='alcance'),
        ),
    ]
