# Generated by Django 6.1 on 2026-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alcance_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciavisitante',
            name='groseria',
            field=models.CharField(choices=[('suave', 'Suave'), ('normal', 'Normal'), ('sin_filtro', 'Sin filtro')], default='suave', max_length=16, verbose_name='nivel de grosería'),
        ),
    ]
