# Generated by Django 6.1 on 2026-09-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='fecha')),
                ('page_views', models.PositiveIntegerField(verbose_name='paginas vistas')),
                ('visitors', models.PositiveIntegerField(verbose_name='visitantes')),
            ],
            options={
                'verbose_name': 'trafico diario',
                'verbose_name_plural': 'trafico diario',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Primer dia del mes', unique=True, verbose_name='mes')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto')),
            ],
            options={
                'verbose_name': 'gasto mensual',
                'verbose_name_plural': 'gastos mensuales',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Primer dia del mes', unique=True, verbose_name='mes')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='meta de ingresos')),
                ('orders', models.PositiveIntegerField(verbose_name='meta de pedidos')),
                ('visits', models.PositiveIntegerField(verbose_name='meta de visitas')),
            ],
            options={
                'verbose_name': 'meta mensual',
                'verbose_name_plural': 'metas mensuales',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('category', models.CharField(max_length=80, verbose_name='categoria')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio')),
                ('status', models.CharField(choices=[('active', 'Disponible'), ('low_stock', 'Pocas unidades'), ('out_of_stock', 'Agotado')], default='active', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('country', models.CharField(max_length=80, verbose_name='pais')),
                ('country_code', models.CharField(max_length=2, verbose_name='codigo ISO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country_code'], name='dashboard_c_country_24469e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='codigo')),
                ('status', models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente'), ('refunded', 'Devuelto'), ('failed', 'Fallido')], default='paid', max_length=16, verbose_name='estado')),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta de credito'), ('pse', 'PSE'), ('transfer', 'Transferencia'), ('cash', 'Efectivo'), ('wallet', 'Billetera digital')], max_length=16, verbose_name='medio de pago')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total')),
                ('placed_at', models.DateTimeField(verbose_name='fecha')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.order', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='dashboard.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'linea de pedido',
                'verbose_name_plural': 'lineas de pedido',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-placed_at'], name='dashboard_o_placed__20813c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-placed_at'], name='dashboard_o_status_cc498c_idx'),
        ),
    ]
