# Generated by Django 6.1 on 2026-09-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sobregasto', 'Gastos por encima de los ingresos'), ('resumen', 'Resumen del mes')], max_length=16, verbose_name='tipo')),
                ('mes', models.DateField(verbose_name='mes')),
                ('enviado_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado')),
            ],
            options={
                'verbose_name': 'aviso enviado',
                'verbose_name_plural': 'avisos enviados',
                'ordering': ['-enviado_at'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'mes'), name='aviso_unico_por_mes')],
            },
        ),
    ]
