# Generated by Django 6.1 on 2026-10-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_sugerencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante', models.CharField(max_length=64, unique=True, verbose_name='visitante')),
                ('datos', models.JSONField(default=dict, verbose_name='datos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'ajuste visual',
                'verbose_name_plural': 'ajustes visuales',
            },
        ),
    ]
