# Generated by Django 6.1 on 2026-10-01 18:14

import django.core.validators
from django.db import migrations, models

import finanzas.conceptos


def agrupar(apps, schema_editor):
    """Le pone grupo a los conceptos conocidos que estén en la tabla."""
    Sugerencia = apps.get_model("finanzas", "Sugerencia")
    for nombre, grupo in finanzas.conceptos.GRUPOS_SEMILLA.items():
        Sugerencia.objects.filter(clave=finanzas.conceptos.clave(nombre)).update(
            grupo=grupo
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_ajustevisual'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='grupo',
            field=models.CharField(choices=[('deuda', 'Deudas'), ('familia', 'Familia'), ('comida', 'Comida'), ('transporte', 'Transporte'), ('mascotas', 'Mascotas'), ('hogar', 'Hogar y servicios'), ('gustos', 'Gustos y salidas'), ('otro', 'Otros')], default='otro', max_length=16, verbose_name='grupo'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='presupuesto',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='presupuesto mensual'),
        ),
        migrations.RunPython(agrupar, migrations.RunPython.noop),
    ]
