# Generated by Django 6.1 on 2026-10-01 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_grupo_y_presupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('clave', models.CharField(editable=False, max_length=100, unique=True, verbose_name='clave')),
                ('saldo_inicial', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='saldo al empezar')),
                ('fecha_inicio', models.DateField(verbose_name='desde')),
                ('cupo', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='cupo')),
                ('cuota', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='cuota mensual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'crédito',
                'verbose_name_plural': 'créditos',
                'ordering': ['nombre'],
            },
        ),
    ]
