# Generated by Django 6.1 on 2026-10-01 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='tasa_ea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='tasa efectiva anual (%)'),
        ),
    ]
