# Generated by Django 6.1 on 2026-10-01 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_tasa_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tipo', models.CharField(choices=[('intereses', 'Intereses'), ('manejo', 'Cuota de manejo'), ('seguro', 'Seguro'), ('mora', 'Intereses de mora'), ('otro', 'Otro cargo')], default='intereses', max_length=16, verbose_name='tipo')),
                ('valor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='valor')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='finanzas.credito', verbose_name='crédito')),
            ],
            options={
                'verbose_name': 'cargo de crédito',
                'verbose_name_plural': 'cargos de créditos',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
