# Generated by Django 6.1 on 2026-10-01 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_cargo_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('clave', models.CharField(editable=False, max_length=100, unique=True, verbose_name='clave')),
                ('monto', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='monto mensual')),
                ('dia_pago', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día de pago')),
                ('fecha_inicio', models.DateField(verbose_name='desde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'gasto fijo',
                'verbose_name_plural': 'gastos fijos',
                'ordering': ['nombre'],
            },
        ),
    ]
