# Generated by Django 6.1 on 2026-10-01 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_gasto_fijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='costo_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de cada pago en intereses y seguros'),
        ),
    ]
