# Generated by Django 6.1 on 2026-10-01 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_costo_por_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='salario mensual')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'configuración de finanzas',
                'verbose_name_plural': 'configuración de finanzas',
            },
        ),
        migrations.AddField(
            model_name='gastofijo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='hasta'),
        ),
    ]
