# Generated by Django 6.1 on 2026-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('role', models.CharField(max_length=70, verbose_name='cargo')),
                ('company', models.CharField(max_length=90, verbose_name='empresa')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='ciudad')),
                ('start', models.CharField(help_text='AAAA-MM', max_length=7, verbose_name='inicio')),
                ('end', models.CharField(blank=True, help_text='AAAA-MM', max_length=7, verbose_name='fin')),
                ('current', models.BooleanField(default=False, verbose_name='cargo actual')),
                ('bullets', models.TextField(blank=True, help_text='Una por linea', verbose_name='funciones')),
                ('stack', models.TextField(blank=True, help_text='Separadas por comas', verbose_name='tecnologias')),
            ],
            options={
                'verbose_name': 'experiencia',
                'verbose_name_plural': 'experiencias',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('kind', models.CharField(choices=[('education', 'Formacion'), ('certification', 'Curso o certificacion')], db_index=True, max_length=16, verbose_name='tipo')),
                ('title', models.CharField(max_length=90, verbose_name='titulo')),
                ('institution', models.CharField(max_length=60, verbose_name='institucion')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='ciudad')),
                ('year', models.CharField(blank=True, max_length=12, verbose_name='anio')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'formacion',
                'verbose_name_plural': 'formacion',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('title', models.CharField(max_length=70, verbose_name='titulo')),
                ('text', models.TextField(max_length=320, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'punto del perfil',
                'verbose_name_plural': 'puntos del perfil',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('name', models.CharField(max_length=30, verbose_name='idioma')),
                ('level', models.CharField(choices=[('nativo', 'Nativo'), ('avanzado', 'Avanzado'), ('intermedio', 'Intermedio'), ('basico', 'Basico')], default='intermedio', max_length=16, verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('label', models.CharField(max_length=40, verbose_name='etiqueta')),
                ('value', models.CharField(max_length=60, verbose_name='valor')),
            ],
            options={
                'verbose_name': 'dato personal',
                'verbose_name_plural': 'datos personales',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('name', models.CharField(max_length=70, verbose_name='nombre')),
                ('relation', models.CharField(max_length=50, verbose_name='relacion')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=90, verbose_name='correo')),
            ],
            options={
                'verbose_name': 'referencia',
                'verbose_name_plural': 'referencias',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='apellidos')),
                ('title', models.CharField(max_length=60, verbose_name='cargo')),
                ('initials', models.CharField(max_length=4, verbose_name='iniciales')),
                ('address', models.CharField(blank=True, max_length=160, verbose_name='direccion')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=90, verbose_name='correo')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('website_label', models.CharField(blank=True, max_length=60, verbose_name='texto del enlace')),
                ('website_note', models.CharField(blank=True, max_length=90, verbose_name='nota del enlace')),
                ('summary', models.TextField(blank=True, max_length=400, verbose_name='resumen')),
                ('show_reference_contacts', models.BooleanField(default=True, help_text='Apagalo para ocultar telefono y correo de las referencias.', verbose_name='mostrar contacto de las referencias')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('skills', models.TextField(blank=True, help_text='Separadas por comas', verbose_name='herramientas')),
            ],
            options={
                'verbose_name': 'grupo de herramientas',
                'verbose_name_plural': 'grupos de herramientas',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
